name: Build Docker Image
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
          
        - name: Build Docker image
          run: docker build -t url-shortener -f UrlShortener/Dockerfile UrlShortener
          
        # Optional - Add a step to verify the build was successful
        - name: Test image
          run: docker image inspect url-shortener